# Generated by Django 5.2.12 on 2026-07-28 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("supply", "0003_qualification_uniq_qualification_per_org_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierorg",
            name="kind",
            field=models.CharField(
                choices=[("supplier", "Supplier"), ("implementing_partner", "Implementing partner")],
                default="supplier",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="supplynode",
            name="adm1_code",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.CreateModel(
            name="CaseloadEstimate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("country", models.CharField(max_length=2)),
                ("adm1_code", models.CharField(max_length=16)),
                ("adm1_name", models.CharField(max_length=160)),
                ("month", models.DateField(help_text="First day of the month this estimate covers.")),
                ("ipc_phase", models.PositiveSmallIntegerField()),
                ("under5_population", models.PositiveIntegerField()),
                ("children_sam", models.PositiveIntegerField()),
                ("source_note", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "supply_caseload_estimate",
                "ordering": ["country", "adm1_name", "month"],
                "constraints": [
                    models.UniqueConstraint(fields=("adm1_code", "month"), name="uniq_caseload_per_district_month")
                ],
            },
        ),
        migrations.CreateModel(
            name="DistributionPlan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("scheduled_for", models.DateField()),
                ("expected_children", models.PositiveIntegerField()),
                ("cartons_required", models.DecimalField(decimal_places=2, max_digits=12)),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distribution_plans",
                        to="supply.supplierorg",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distribution_plans",
                        to="supply.supplynode",
                    ),
                ),
            ],
            options={
                "db_table": "supply_distribution_plan",
                "ordering": ["scheduled_for", "site__name"],
            },
        ),
        migrations.CreateModel(
            name="DistributionRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("distributed_on", models.DateField()),
                ("cartons_dispensed", models.DecimalField(decimal_places=2, max_digits=12)),
                ("children_served", models.PositiveIntegerField()),
                ("batch_lot", models.CharField(max_length=32)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distribution_records",
                        to="supply.supplierorg",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="records",
                        to="supply.distributionplan",
                    ),
                ),
                (
                    "shipment_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="distribution_records",
                        to="supply.shipmentline",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distribution_records",
                        to="supply.supplynode",
                    ),
                ),
            ],
            options={
                "db_table": "supply_distribution_record",
                "ordering": ["-distributed_on", "site__name"],
            },
        ),
        migrations.CreateModel(
            name="ChildOutcome",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("anon_id", models.CharField(max_length=32, unique=True)),
                ("batch_lot", models.CharField(max_length=32)),
                ("admitted_on", models.DateField()),
                ("admission_muac_mm", models.PositiveSmallIntegerField()),
                ("measurements", models.JSONField(default=list)),
                (
                    "discharge_status",
                    models.CharField(
                        choices=[
                            ("recovered", "Recovered"),
                            ("defaulted", "Defaulted"),
                            ("transferred", "Transferred to inpatient care"),
                            ("non_response", "Non Response"),
                            ("in_treatment", "In Treatment"),
                        ],
                        default="in_treatment",
                        max_length=16,
                    ),
                ),
                ("discharged_on", models.DateField(blank=True, null=True)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_outcomes",
                        to="supply.supplierorg",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_outcomes",
                        to="supply.supplynode",
                    ),
                ),
                (
                    "distribution_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_outcomes",
                        to="supply.distributionrecord",
                    ),
                ),
            ],
            options={
                "db_table": "supply_child_outcome",
                "ordering": ["site__name", "admitted_on"],
            },
        ),
        migrations.CreateModel(
            name="SupplyAction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("expedite", "Expedite"),
                            ("reallocate", "Reallocate"),
                            ("split_lot", "Split Lot"),
                            ("mini_tender", "Mini Tender"),
                        ],
                        max_length=24,
                    ),
                ),
                ("actor", models.CharField(max_length=160)),
                ("rationale", models.TextField()),
                ("effect", models.CharField(blank=True, max_length=255)),
                ("quantity", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shipment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_by_actions",
                        to="supply.shipment",
                    ),
                ),
                (
                    "source_node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actions_from",
                        to="supply.supplynode",
                    ),
                ),
                (
                    "target_node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actions_to",
                        to="supply.supplynode",
                    ),
                ),
            ],
            options={
                "db_table": "supply_action",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShortfallSignal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("raised_on", models.DateField()),
                ("needed_by", models.DateField()),
                ("children_affected", models.PositiveIntegerField()),
                ("cartons_short", models.DecimalField(decimal_places=2, max_digits=12)),
                ("note", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("acknowledged", "Acknowledged"), ("resolved", "Resolved")],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shortfall_signals",
                        to="supply.supplierorg",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shortfall_signals",
                        to="supply.supplynode",
                    ),
                ),
                (
                    "resolved_by_action",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolves_signals",
                        to="supply.supplyaction",
                    ),
                ),
            ],
            options={
                "db_table": "supply_shortfall_signal",
                "ordering": ["-raised_on", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="distributionplan",
            constraint=models.UniqueConstraint(
                fields=("site", "scheduled_for"), name="uniq_distribution_per_site_day"
            ),
        ),
    ]
