# Generated by Django 5.2.12 on 2026-07-28 03:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("supply", "0004_supplierorg_kind_supplynode_adm1_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplynode",
            name="catchment_weight",
            field=models.FloatField(default=1.0),
        ),
    ]
