# Generated by Django 5.2.12 on 2026-07-24 19:01

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("occurred_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("username", models.CharField(blank=True, default="", max_length=150)),
                ("user_email", models.CharField(blank=True, default="", max_length=254)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("list", "List/query records"),
                            ("read", "Read record"),
                            ("export", "Bulk export/fetch"),
                            ("create", "Create record"),
                            ("update", "Update record"),
                            ("delete", "Delete record"),
                            ("login", "Login"),
                            ("login_failed", "Login failed"),
                            ("logout", "Logout"),
                            ("access_denied", "Access denied"),
                            ("review", "Audit log review"),
                            ("canary", "Pipeline canary"),
                        ],
                        max_length=20,
                    ),
                ),
                ("resource_type", models.CharField(blank=True, db_index=True, default="", max_length=100)),
                ("resource_id", models.CharField(blank=True, default="", max_length=100)),
                ("record_count", models.IntegerField(blank=True, null=True)),
                ("opportunity_id", models.IntegerField(blank=True, null=True)),
                ("program_id", models.IntegerField(blank=True, null=True)),
                ("organization_id", models.IntegerField(blank=True, null=True)),
                ("labs_only", models.BooleanField(default=False)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("web", "Web request"),
                            ("mcp", "MCP tool call"),
                            ("celery", "Background task"),
                            ("script", "Script/management command"),
                            ("system", "System"),
                        ],
                        default="system",
                        max_length=10,
                    ),
                ),
                ("ip_address", models.CharField(blank=True, default="", max_length=45)),
                ("user_agent", models.CharField(blank=True, default="", max_length=300)),
                ("request_id", models.CharField(blank=True, default="", max_length=36)),
                ("path", models.CharField(blank=True, default="", max_length=300)),
                (
                    "outcome",
                    models.CharField(
                        choices=[("success", "Success"), ("failure", "Failure")], default="success", max_length=10
                    ),
                ),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "labs_audit_event",
                "ordering": ["-occurred_at"],
                "indexes": [
                    models.Index(fields=["user", "-occurred_at"], name="labs_audit__user_id_b63857_idx"),
                    models.Index(fields=["action", "-occurred_at"], name="labs_audit__action_c60267_idx"),
                    models.Index(fields=["opportunity_id", "-occurred_at"], name="labs_audit__opportu_5f0111_idx"),
                ],
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="auditevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="76e4f381176d2a24e37a566dc5d9ccc5967a7c73",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_cc6e6",
                    table="labs_audit_event",
                    when="BEFORE",
                ),
            ),
        ),
    ]
