# Generated by Django 5.2.12 on 2026-07-25 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit_trail", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditevent",
            name="query_string",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="auditevent",
            name="action",
            field=models.CharField(
                choices=[
                    ("list", "List/query records"),
                    ("read", "Read record"),
                    ("export", "Bulk export/fetch"),
                    ("create", "Create record"),
                    ("update", "Update record"),
                    ("delete", "Delete record"),
                    ("page_view", "Page view"),
                    ("login", "Login"),
                    ("login_failed", "Login failed"),
                    ("logout", "Logout"),
                    ("access_denied", "Access denied"),
                    ("review", "Audit log review"),
                    ("canary", "Pipeline canary"),
                ],
                max_length=20,
            ),
        ),
    ]
