# Generated by Django 5.2.12 on 2026-07-28 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PulseIngestHealth",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tier", models.CharField(max_length=24, unique=True)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("last_error_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("consecutive_failures", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="PulseOpportunity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("opportunity_id", models.IntegerField(db_index=True, unique=True)),
                ("name", models.CharField(blank=True, max_length=300)),
                ("org_slug", models.CharField(blank=True, max_length=120)),
                ("program_id", models.IntegerField(blank=True, db_index=True, null=True)),
                ("country", models.CharField(blank=True, max_length=2)),
                ("service_slug", models.CharField(blank=True, max_length=48)),
                ("is_active", models.BooleanField(default=False)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("lifetime_visit_count", models.IntegerField(default=0)),
                ("currency", models.CharField(blank=True, max_length=8)),
                ("budget_per_visit", models.BigIntegerField(blank=True, null=True)),
                ("total_budget", models.BigIntegerField(blank=True, null=True)),
                ("usd_per_service", models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "pulse opportunities",
            },
        ),
        migrations.CreateModel(
            name="PulseScalar",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(max_length=64, unique=True)),
                ("value", models.JSONField(default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PulseCursor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("opportunity_id", models.IntegerField(db_index=True)),
                ("endpoint", models.CharField(max_length=48)),
                ("last_id", models.BigIntegerField(blank=True, null=True)),
                ("newest_sync_ts", models.DateTimeField(blank=True, null=True)),
                ("last_polled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("hot", "Hot — visit in the last 6h"),
                            ("warm", "Warm — visit in the last 7d"),
                            ("cold", "Cold — visit in the last 90d"),
                            ("dormant", "Dormant — nothing recent"),
                        ],
                        db_index=True,
                        default="cold",
                        max_length=12,
                    ),
                ),
                ("backfill_complete", models.BooleanField(default=False)),
                ("backfill_oldest_id", models.BigIntegerField(blank=True, null=True)),
                ("consecutive_failures", models.IntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
            ],
            options={
                "unique_together": {("opportunity_id", "endpoint")},
            },
        ),
        migrations.CreateModel(
            name="PulseEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("connect_visit_id", models.BigIntegerField(db_index=True, unique=True)),
                ("opportunity_id", models.IntegerField(db_index=True)),
                ("program_id", models.IntegerField(blank=True, db_index=True, null=True)),
                ("org_slug", models.CharField(blank=True, max_length=120)),
                ("field_ts", models.DateTimeField(db_index=True)),
                ("sync_ts", models.DateTimeField(db_index=True)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lon", models.FloatField(blank=True, null=True)),
                ("country", models.CharField(blank=True, db_index=True, max_length=2)),
                ("status", models.CharField(db_index=True, max_length=32)),
                ("flagged", models.BooleanField(default=False)),
                ("flag_type", models.CharField(blank=True, max_length=48)),
                ("review_status", models.CharField(blank=True, max_length=24)),
                ("service_slug", models.CharField(blank=True, max_length=48)),
                ("worker_hash", models.CharField(blank=True, max_length=64)),
                ("usd_to_worker", models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["field_ts", "opportunity_id"], name="pulse_pulse_field_t_c1e899_idx"),
                    models.Index(fields=["sync_ts"], name="pulse_pulse_sync_ts_2d86a6_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PulsePublicToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("token", models.CharField(db_index=True, max_length=64, unique=True)),
                ("label", models.CharField(blank=True, max_length=200)),
                ("layout_slug", models.CharField(default="nightmap", max_length=64)),
                ("show_partner_names", models.BooleanField(default=True)),
                ("revoked", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_viewed_at", models.DateTimeField(blank=True, null=True)),
                ("view_count", models.IntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pulse_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PulseRollup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bucket_hour", models.DateTimeField(db_index=True)),
                ("opportunity_id", models.IntegerField(db_index=True)),
                ("status", models.CharField(max_length=32)),
                ("n", models.IntegerField(default=0)),
                ("flagged_n", models.IntegerField(default=0)),
                ("usd", models.DecimalField(decimal_places=4, default=0, max_digits=14)),
            ],
            options={
                "indexes": [models.Index(fields=["bucket_hour", "status"], name="pulse_pulse_bucket__50879a_idx")],
                "unique_together": {("bucket_hour", "opportunity_id", "status")},
            },
        ),
    ]
