# Generated by Django 5.2.12 on 2026-07-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pulse", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PulseGridCell",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("lat_q", models.IntegerField()),
                ("lon_q", models.IntegerField()),
                ("country", models.CharField(blank=True, db_index=True, max_length=2)),
                ("service_slug", models.CharField(blank=True, max_length=48)),
                ("n", models.IntegerField(default=0)),
                ("approved_n", models.IntegerField(default=0)),
                ("flagged_n", models.IntegerField(default=0)),
                ("first_ts", models.DateTimeField(blank=True, null=True)),
                ("last_ts", models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                "indexes": [models.Index(fields=["country", "n"], name="pulse_pulse_country_101959_idx")],
                "unique_together": {("lat_q", "lon_q", "service_slug")},
            },
        ),
        migrations.CreateModel(
            name="PulseWork",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("work_key", models.CharField(db_index=True, max_length=64, unique=True)),
                ("opportunity_id", models.IntegerField(db_index=True)),
                ("program_id", models.IntegerField(blank=True, db_index=True, null=True)),
                ("org_slug", models.CharField(blank=True, max_length=120)),
                ("worker_hash", models.CharField(blank=True, max_length=64)),
                ("payment_unit_id", models.IntegerField(blank=True, null=True)),
                ("service_slug", models.CharField(blank=True, max_length=48)),
                ("country", models.CharField(blank=True, db_index=True, max_length=2)),
                ("status", models.CharField(db_index=True, max_length=32)),
                ("created_ts", models.DateTimeField(db_index=True)),
                ("status_ts", models.DateTimeField(blank=True, null=True)),
                ("payment_date", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("approved_count", models.IntegerField(default=0)),
                ("completed_count", models.IntegerField(default=0)),
                ("usd_to_worker", models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ("usd_to_org", models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["created_ts", "opportunity_id"], name="pulse_pulse_created_ffa6c0_idx"),
                    models.Index(fields=["status", "created_ts"], name="pulse_pulse_status_3a21e7_idx"),
                ],
            },
        ),
    ]
